import os
import sys
from py_gd_auth_cobhan.lib import CobhanDemoLib, AuthConfig

lib_file = sys.argv[1]

print(f"Testing: {lib_file}")

if os.path.isfile(lib_file):
    lib = CobhanDemoLib.from_library_file(str(os.path.abspath(lib_file)))
else:
    print("Library file is missing")
    sys.exit(255)

print(f"Loaded: {lib_file}")

dev_token = "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogIjV5UXU0WlhXMUEifQ.eyJhdXRoIjogImJhc2ljIiwgImZ0YyI6IDEsICJpYXQiOiAxNjYyMTU5ODUzLCAianRpIjogIlhrSjNzOTE5Z3F1NVlZaW9oSW1QTnciLCAidHlwIjogImlkcCIsICJ2YXQiOiAxNjYyMTU5ODUzLCAiZmFjdG9ycyI6IHsia19wdyI6IDE2NjIxNTk4NTN9LCAicGVyIjogdHJ1ZSwgImhiaSI6IDE2NjIxNTk4NTMsICJzaG9wcGVySWQiOiAiMTY4MzE3MyIsICJjaWQiOiAiZTY2NWFlNGEtODE5OS00Yjg5LWI1ZmEtZTExOTFiYWZiZjY3IiwgInBsaWQiOiAiMSIsICJwbHQiOiAxLCAic2hhcmQiOiAiMDEwMiIsICJpZGVudGl0eSI6ICIwYjQ5NjlhMC1mMWI2LTExZTgtODM2OS0wMjQyYzBhOGIwMDIifQ.1c8Gw4I5j5-mqiY1gyMXHEPleAggUhB63-DrLqsRgiuzTe4YQ0Qk5VgDab1RphivU410rDMB2_jTLN4Sw6zYBPxnKcHa-a7rxzDmdzJ6kttxqckHyFhOWeqAwMfuYWtuVsu7mpBbyNroSW8hrMun-pYAoc1uvTvIUIIgfrgY7KBrPXaT6GtjH_Io2yW13ihYq3hO_I5TkzbnTVUBkteIS-t390EJQDb6gMMNQTzx5FI7uSC_klBIGMCQXBnRMXpzLQMEaTdIRafRD0utZ2dA4qrHMwVHmtAlKxRJgfLwsOboqRmWXCaWNAvJphncj_cjw26i_9XLMstYB6YsKNcuOQ"
test_token = "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogIlR4VzJnbWV1N2cifQ.eyJhdXRoIjogImJhc2ljIiwgImZ0YyI6IDEsICJpYXQiOiAxNjYyNTY1MDYyLCAianRpIjogInBVaXd3WUlTVlVidXpwZWlvMXBqN3ciLCAidHlwIjogImlkcCIsICJ2YXQiOiAxNjYyNTY1MDYyLCAiZmFjdG9ycyI6IHsia19wdyI6IDE2NjI1NjUwNjJ9LCAicGVyIjogdHJ1ZSwgImhiaSI6IDE2NjI1NjUwNjIsICJzaG9wcGVySWQiOiAiMjg4NzI5MiIsICJjaWQiOiAiOGNlOWRlOTgtMjRiNi00YjFmLTllNzItNWIwOWU0YWI2ZDk3IiwgInBsaWQiOiAiMSIsICJwbHQiOiAxLCAic2hhcmQiOiAiMDAwMCIsICJpZGVudGl0eSI6ICI5YWI0MWNhZS1mNzJjLTExZTgtOTYzYi1mYTE2M2VkNWMyMzcifQ.np43IhQzauH69fcz3AettkIbnJexzAmtC-z95zkOr3R3pmAfGet8AxyBe-6HphF0mo73mxys1v-YsufVfMZ8kBY8kuBr4paWXPw0YocoUgsWyn45qvDBwUTDLKRa6nUvMCL2oUlQ8n4Vpq3N5edsW8EOpV9kVSOIoLcmSwdeGiWIwgY-cNNakq4Hy7QbEGR-FkU9MNK3WfBqY_jFs-QrSExG6lJyFyh2DcZCkRoVE3mS0QKRtHUBwPzUaC5OXDXuy_NcPN4m9e9PtEOSfoXQpXhCJB1Uy0Q5aCW1bscvj9-t0joZLjH5j5mXfl83rtLCgpoTQSQKjHsxNKnUuhumGQ"
config = AuthConfig(host="dev-godaddy.com")

token_result = lib.parse(config, dev_token)
print(f"Token result: {token_result}")